# Pytorch Backprop (Advanced)

## Softmax
Let's first focus on the softmax function which is a $x \to y: R^{n} \rightarrow R^{n}$ mapping where any output element depends on all input elements, and its Jacobian matrix is somewhat non-trivial. These make it a good example function to study backprop:

In [184]:
import torch
from torch.nn.functional import softmax

x = torch.randn((5,), requires_grad=True) # a test input vector
y = softmax(x, dim=-1)
print(x)
print(y)

y_grad = torch.randn((5,), requires_grad=False) 

y.backward(y_grad, retain_graph=True)
print(x.grad)
#assert torch.allclose(x.grad, y.grad_fn(y_grad)) # same as calling y.grad_fn()
#assert torch.allclose(x.grad, torch.autograd.grad(y, x, y_grad)[0]) # an alternative way to get x.grad

tensor([-1.5701, -0.0628, -1.8929, -0.9927, -1.4878], requires_grad=True)
tensor([0.1098, 0.4958, 0.0795, 0.1956, 0.1192], grad_fn=<SoftmaxBackward0>)
tensor([-0.0072, -0.1155,  0.0580,  0.1067, -0.0420])


Assume the hypotheticcal scaler loss function (at the root of our computation graph) is $L$, the output value `x.grad` $\nabla_x^T L $, according to the [chain rule](../math/chain_rule_and_jacobian.ipynb), is derived from $\nabla_{y}^T L \cdot J_x y$ where  $\nabla_{y} L$ is just `y_grad`.

## Softmax (Naively Batched)

We can also compute the "batched" version. In backprop context, batch means the same and (non-batched) input vector $x$ with (batched) `y_grad` (if $x$ are batched and are different, the Jacobian matrix's values $\left. J_{x}y \right|_{x = x_1, x_2, ..., x_B}$ would be different):

In [185]:
Y_grad = torch.randn((3, 5), requires_grad=False)  # a test **batch**
# let's set its first row to be identical to our above vector, just make it easier to observe the differences.
Y_grad[0, :] = y_grad.detach()
print(Y_grad)

# y = softmax(x, dim=-1) # same x, same, y, no need to do it again!

x.grad.zero_()
y.backward(Y_grad[0, :], retain_graph=True)
print(x.grad) # same as the old x.grad

x.grad.zero_()
y.backward(Y_grad[1, :], retain_graph=True)
print(x.grad)

x.grad.zero_()
y.backward(Y_grad[2, :], retain_graph=True)
print(x.grad)

tensor([[-0.1278, -0.2947,  0.6674,  0.4836, -0.4141],
        [-0.9572,  0.3029,  1.2252,  0.3351,  0.7663],
        [-0.9017,  2.3485, -0.6726,  0.6428,  0.2113]])
tensor([-0.0072, -0.1155,  0.0580,  0.1067, -0.0420])
tensor([-0.1380,  0.0017,  0.0736,  0.0070,  0.0557])
tensor([-0.2267,  0.5879, -0.1459, -0.1017, -0.1134])


## VJP- and JVP-Batched
A VJP (Vector–Jacobian Product) is simply a term to describe the math form:
$$
\underbrace{\mathbf{v}^\top}_{\text{cotangents}}
\underbrace{\frac{\partial f(\mathbf{x})}{\partial \mathbf{x}}}_{\substack{\text{Jacobian of }f \\ \text{w.r.t. primals}}}
$$

similarly, JVP is
$$
\underbrace{\frac{\partial f(\mathbf{x})}{\partial \mathbf{x}}}_{\substack{\text{Jacobian of }f \\ \text{w.r.t. primals}}}
\underbrace{\mathbf{u}}_{\text{tangents}}
$$

In [186]:
y2, vjp_fn = torch.func.vjp(softmax, x) # torch.func.vjp(func, *primals)
assert torch.allclose(y, y2)

In [187]:
vjp_fn(y_grad) # y_grad is the "v"

(tensor([-0.0072, -0.1155,  0.0580,  0.1067, -0.0420],
        grad_fn=<SoftmaxBackwardDataBackward0>),)

However, `vjp_fn` cannot take in batched y_grad, i.e., Y_grad:

In [188]:
try:
    vjp_fn(Y_grad)  # error!
except Exception as e:
    print(e)

Mismatch in shape: grad_output[0] has a shape of torch.Size([3, 5]) and output[0] has a shape of torch.Size([5]).


A simple solution is to loop and apply (i.e., `vmap`):

In [189]:
batched_vjp_fn = torch.func.vmap(vjp_fn)
vmap_X_grad = batched_vjp_fn(Y_grad)[0].detach()
assert torch.allclose(vmap_X_grad, torch.vstack([
    vjp_fn(Y_grad[0, :])[0].detach(),
    vjp_fn(Y_grad[1, :])[0].detach(),
    vjp_fn(Y_grad[2, :])[0].detach(),
]))
vmap_X_grad

tensor([[-0.0072, -0.1155,  0.0580,  0.1067, -0.0420],
        [-0.1380,  0.0017,  0.0736,  0.0070,  0.0557],
        [-0.2267,  0.5879, -0.1459, -0.1017, -0.1134]])

where each row corresponds to exactly the single-batched x.grad after each `y.backward` above.

Due to the efficiency of only compute Jacobian matrix once (via the `vjp` function), this batched version runs faster.$^{1}$

Similarly, for `jvp` (note that pytorch jvp takes in tuples of *multiple primals or tangents* compared to `vjp`):

In [201]:
# reset
x.grad.zero_()
y = softmax(x, dim=-1)
y_grad = torch.randn((5,), requires_grad=False)
y.backward(y_grad)
print(y_grad)

# Move vjp here for easy comparison:
# y2, vjp_fn = torch.func.vjp(softmax, x) # torch.func.vjp(func, *primals)
y3, jvp_out = torch.func.jvp(softmax, (x, ), (x.grad, )) # torch.func.jvp(func, primals, tangents)
assert torch.allclose(y, y3)
print(jvp_out)

tensor([ 0.3941, -1.3663,  0.7759,  0.4256,  0.6555])
tensor([ 0.0284, -0.1503,  0.0211,  0.0654,  0.0355], grad_fn=<MulBackward0>)


## Jacobian

Above manipulations all hide the actual Jacobian matrix from our sight. How to retrieve it? Simple! Just constract an eye matrix and retrieve it row by row:

$$
\begin{bmatrix}
e_1 \\
e_2 \\
... \\
e_5
\end{bmatrix}
\cdot [ J_x \; y(x) ]_{5 \times 5} = E_{5 \times 5} \cdot [ J_x \; y(x) ]_{5 \times 5} = [ J_x \; y(x) ]_{5 \times 5}
$$

In [191]:
eye = torch.eye(5, 5)
J = batched_vjp_fn(eye)[0].detach()
print(J)

tensor([[ 0.0978, -0.0544, -0.0087, -0.0215, -0.0131],
        [-0.0544,  0.2500, -0.0394, -0.0970, -0.0591],
        [-0.0087, -0.0394,  0.0732, -0.0156, -0.0095],
        [-0.0215, -0.0970, -0.0156,  0.1574, -0.0233],
        [-0.0131, -0.0591, -0.0095, -0.0233,  0.1050]])


Let's verify whether this matrix is indeed the Jacobian matrix:

In [192]:
x.grad.zero_()
y = softmax(x, dim=-1)
y_grad = torch.randn((5,), requires_grad=False)
y.backward(y_grad)
assert torch.allclose(x.grad, y_grad @ J)

The above vjp-vmap composition to get the Jacobian matrix can be also replaced by the `jacrev` function, which stands for "Jacobian-of-Reverse" in the reverse mode autodiff:

In [193]:
torch.func.jacrev(softmax)(x)

tensor([[ 0.0978, -0.0544, -0.0087, -0.0215, -0.0131],
        [-0.0544,  0.2500, -0.0394, -0.0970, -0.0591],
        [-0.0087, -0.0394,  0.0732, -0.0156, -0.0095],
        [-0.0215, -0.0970, -0.0156,  0.1574, -0.0233],
        [-0.0131, -0.0591, -0.0095, -0.0233,  0.1050]],
       grad_fn=<ViewBackward0>)

Similarly, there is a `jacfwd` for forward mode autodiff.
`jacfwd` uses forward-mode AD. It is implemented as a composition of jvp-vmap.

In [194]:
torch.func.jacfwd(softmax)(x)

tensor([[ 0.0978, -0.0544, -0.0087, -0.0215, -0.0131],
        [-0.0544,  0.2500, -0.0394, -0.0970, -0.0591],
        [-0.0087, -0.0394,  0.0732, -0.0156, -0.0095],
        [-0.0215, -0.0970, -0.0156,  0.1574, -0.0233],
        [-0.0131, -0.0591, -0.0095, -0.0233,  0.1050]],
       grad_fn=<ViewBackward0>)

`jacfwd` and `jacrev` can be substituted for each other but they have different performance characteristics:$^1$
> In reverse-mode AD, we are computing the jacobian row-by-row, while in forward-mode AD (which computes Jacobian-vector products), we are computing it column-by-column. The Jacobian matrix has M rows and N columns, so if it is taller or wider one way we may prefer the method that deals with fewer rows or columns.

## Reference
1. https://docs.pytorch.org/functorch/stable/notebooks/jacobians_hessians.html